<a href="https://colab.research.google.com/github/nihalbaig0/dphi_notebooks/blob/master/Heart_Disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Heart Disease Prediction

##Getting data from Kaggle

In [ ]:
 ! pip install -q kaggle

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"nihalbaig","key":"69d2116168efec478cc51c3370260229"}'}

In [ ]:
! mkdir ~/.kaggle

In [ ]:
! cp kaggle.json ~/.kaggle/

In [ ]:
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d sulianova/cardiovascular-disease-dataset

  0% 0.00/742k [00:00<?, ?B/s]
100% 742k/742k [00:00<00:00, 50.7MB/s]


In [ ]:
!unzip \*.zip && rm *.zip

Archive:  cardiovascular-disease-dataset.zip
  inflating: cardio_train.csv        


##Importing Libraries 

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


In [ ]:
df=pd.read_csv("cardio_train.csv",sep=';')
df.head()

id    age  gender  height  weight  ...  gluc  smoke  alco  active  cardio
0   0  18393       2     168    62.0  ...     1      0     0       1       0
1   1  20228       1     156    85.0  ...     1      0     0       1       1
2   2  18857       1     165    64.0  ...     1      0     0       0       1
3   3  17623       2     169    82.0  ...     1      0     0       1       1
4   4  17474       1     156    56.0  ...     1      0     0       0       0

[5 rows x 13 columns]

## Minimizing age Column

In [ ]:
#Days to Years
df['age']=df['age']/365

In [ ]:
df.head()

id        age  gender  height  weight  ...  gluc  smoke  alco  active  cardio
0   0  50.391781       2     168    62.0  ...     1      0     0       1       0
1   1  55.419178       1     156    85.0  ...     1      0     0       1       1
2   2  51.663014       1     165    64.0  ...     1      0     0       0       1
3   3  48.282192       2     169    82.0  ...     1      0     0       1       1
4   4  47.873973       1     156    56.0  ...     1      0     0       0       0

[5 rows x 13 columns]

In [ ]:
df.describe()

id           age  ...        active        cardio
count  70000.000000  70000.000000  ...  70000.000000  70000.000000
mean   49972.419900     53.339358  ...      0.803729      0.499700
std    28851.302323      6.759594  ...      0.397179      0.500003
min        0.000000     29.583562  ...      0.000000      0.000000
25%    25006.750000     48.394521  ...      1.000000      0.000000
50%    50001.500000     53.980822  ...      1.000000      0.000000
75%    74889.250000     58.430137  ...      1.000000      1.000000
max    99999.000000     64.967123  ...      1.000000      1.000000

[8 rows x 13 columns]

## ID Column has no effect

In [ ]:
df=df.drop('id',axis=1)
df.head()

age  gender  height  weight  ap_hi  ...  gluc  smoke  alco  active  cardio
0  50.391781       2     168    62.0    110  ...     1      0     0       1       0
1  55.419178       1     156    85.0    140  ...     1      0     0       1       1
2  51.663014       1     165    64.0    130  ...     1      0     0       0       1
3  48.282192       2     169    82.0    150  ...     1      0     0       1       1
4  47.873973       1     156    56.0    100  ...     1      0     0       0       0

[5 rows x 12 columns]

## Taking out the duplicate Values

In [ ]:
df.duplicated().sum()

24

In [ ]:
df.drop_duplicates(inplace=True)
df.head()

age  gender  height  weight  ap_hi  ...  gluc  smoke  alco  active  cardio
0  50.391781       2     168    62.0    110  ...     1      0     0       1       0
1  55.419178       1     156    85.0    140  ...     1      0     0       1       1
2  51.663014       1     165    64.0    130  ...     1      0     0       0       1
3  48.282192       2     169    82.0    150  ...     1      0     0       1       1
4  47.873973       1     156    56.0    100  ...     1      0     0       0       0

[5 rows x 12 columns]

## Feature Engineering
*Pros* 
- Preparing the proper input dataset, compatible with the machine learning algorithm requirements.
- Improving the performance of machine learning models.

In [ ]:
df['BMI'] = df['weight'] / df['height'] / df['height'] * 10000
df['pulse pressure'] = df['ap_hi'] - df['ap_lo']

In [ ]:
df.head()

age  gender  height  weight  ...  active  cardio        BMI  pulse pressure
0  50.391781       2     168    62.0  ...       1       0  21.967120              30
1  55.419178       1     156    85.0  ...       1       1  34.927679              50
2  51.663014       1     165    64.0  ...       0       1  23.507805              60
3  48.282192       2     169    82.0  ...       1       1  28.710479              50
4  47.873973       1     156    56.0  ...       0       0  23.011177              40

[5 rows x 14 columns]

In [ ]:
X = df.drop(['weight', 'height', 'cardio'], axis=1)
y = df['cardio']

##Splitting Training and Test Data using train_test_split

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=17)

## Another Part of Feature Engineering
### *Scaling*
### Normalization
- Scales all values between 0 and 1

- ![normalization.png](https://miro.medium.com/max/210/1*D3ORMiW9A7GoTezFYbL8LA.png)

### Standardization
- Scales the values while taking into account standard deviation
- Reduces the effect of outliers

- ![standardization](https://miro.medium.com/max/103/1*BcNLM9loyAR3YQLt2hDqqg.png)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [ ]:
X_train.shape

(48983, 11)

## Support Vector Machine

![svc](https://www.freecodecamp.org/news/content/images/2020/06/image-58.png)

In [ ]:
from sklearn.svm import SVC
svc = SVC(gamma='auto')
svc.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred_svc = svc.predict(X_test)

In [ ]:
y_pred_svc

array([1, 0, 1, ..., 0, 1, 0], dtype=int64)

## Confusion Matrix

![precision and recall](https://video.udacity-data.com/topher/2019/May/5cede4d4_screen-shot-2019-05-28-at-6.47.54-pm/screen-shot-2019-05-28-at-6.47.54-pm.png)

- F1 score = 2 * (Precision * Recall) / (Precision + Recall)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred_svc))
print(classification_report(y_test, y_pred_svc))

[[8096 2406]
 [3375 7116]]
              precision    recall  f1-score   support

           0       0.71      0.77      0.74     10502
           1       0.75      0.68      0.71     10491

    accuracy                           0.72     20993
   macro avg       0.73      0.72      0.72     20993
weighted avg       0.73      0.72      0.72     20993



In [ ]:
svc.score(X_test, y_test)

0.7246224932120231

#K-Nearest Neighbors


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=100)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=100, p=2,
                     weights='uniform')

In [ ]:
y_pred_knn = knn.predict(X_test)
print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))

[[7689 2813]
 [3860 6631]]
              precision    recall  f1-score   support

           0       0.67      0.73      0.70     10502
           1       0.70      0.63      0.67     10491

    accuracy                           0.68     20993
   macro avg       0.68      0.68      0.68     20993
weighted avg       0.68      0.68      0.68     20993



In [ ]:
knn.score(X_test, y_test)

0.6821321392845234

## XGBoost Classifier (Winner)

In [ ]:
from xgboost import XGBClassifier
xgb = XGBClassifier(learning_rate=0.02, n_estimators=600)
xgb.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.02, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=600, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
y_pred_xgb = xgb.predict(X_test)

In [ ]:
print(confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))

[[8203 2299]
 [3264 7227]]
              precision    recall  f1-score   support

           0       0.72      0.78      0.75     10502
           1       0.76      0.69      0.72     10491

    accuracy                           0.74     20993
   macro avg       0.74      0.73      0.73     20993
weighted avg       0.74      0.74      0.73     20993



In [ ]:
xgb.score(X_test, y_test)

0.7350069070642595

## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
logreg.score(X_test,y_test)

0.7185252226932787

## A simple Deep learning network using Keras

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

# Instantiate a sequential model
model = Sequential()
# Add input and hidden layer
model.add(Dense(15, input_shape=(11,),activation='relu'))
# Add output layer, use sigmoid
model.add(Dense(1,activation='sigmoid'))

# Compile model
model.compile(optimizer='adam',loss='binary_crossentropy')
# Train model
model.fit(X_train, y_train, epochs=20)



Epoch 1/20
1225/1225 [==============================] - 3s 2ms/step - loss: 0.6475 - val_loss: 0.6088
Epoch 2/20
1225/1225 [==============================] - 3s 2ms/step - loss: 0.6059 - val_loss: 0.5850
Epoch 3/20
1225/1225 [==============================] - 3s 2ms/step - loss: 0.5784 - val_loss: 0.5739
Epoch 4/20
1225/1225 [==============================] - 3s 2ms/step - loss: 0.5864 - val_loss: 0.5702
Epoch 5/20
1225/1225 [==============================] - 3s 2ms/step - loss: 0.5684 - val_loss: 0.5676
Epoch 6/20
1225/1225 [==============================] - 3s 2ms/step - loss: 0.5686 - val_loss: 0.5664
Epoch 7/20
1225/1225 [==============================] - 3s 2ms/step - loss: 0.5614 - val_loss: 0.5653
Epoch 8/20
1225/1225 [==============================] - 3s 2ms/step - loss: 0.5612 - val_loss: 0.5646
Epoch 9/20
1225/1225 [==============================] - 3s 2ms/step - loss: 0.5594 - val_loss: 0.5644
Epoch 10/20
1225/1225 [==============================] - 3s 2ms/step - loss: 0.560

In [ ]:
preds = model.predict(X_test)

In [ ]:
model.evaluate(X_test,y_test)

657/657 [==============================] - 1s 1ms/step - loss: 0.5599


0.559895932674408